name: staffmonitor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.1+58

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  chopper: ^6.1.1
  collection: ^1.17.0
  device_info_plus: ^8.1.0 # Get device info for device id
  dio: ^4.0.4
  drift: ^2.6.0 # reactive persistence database
  dropdown_search: ^2.0.1
  equatable: ^2.0.5
  extended_image: ^7.0.2
  file_picker: ^5.2.5
  flex_color_picker: ^3.1.0
  flutter_background_geolocation: ^4.9.0
  flutter_beep: ^1.0.0 # For terminal beep sound after successful qr scan
  flutter_bloc: ^8.1.2
  flutter_chat_ui: ^1.6.6 #Chat ui
  flutter_colorpicker: ^1.0.3
  flutter_downloader: ^1.7.2
  flutter_local_notifications: ^9.9.1 # For show file upload progress in notification
  flutter_map: ^3.1.0 #open street map
  flutter_map_marker_popup: ^4.0.0 #plugin for popups on map
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  flutter_switch: ^0.3.2  # Switch in calendar tab : show task, show session, show holiday
  flutter_uploader: ^3.0.0-beta.4
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  i18n_extension: ^8.0.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.7
  intl: ^0.17.0
  json_annotation: ^4.4.0
  latlong2: ^0.8.1 #latlng class
  logging: ^1.0.2
  material_design_icons_flutter: 5.0.5955-rc.1
  meta: ^1.8.0
  month_picker_dialog_2: ^0.6.1+2
  path: ^1.8.0
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  pushy_flutter: ^2.0.11
  qr_code_scanner: ^1.0.1
  share_plus: ^4.0.2
  shared_preferences: ^2.0.16
  sqlite3_flutter_libs: ^0.5.0
  sticky_headers: ^0.2.0
  syncfusion_flutter_calendar: ^19.3.44 #to implement calendar for calendar tab
  synchronized: ^3.0.0
  table_calendar: ^3.0.3
  timezone: ^0.8.0
  url_launcher: ^6.0.20
  wakelock: ^0.6.1+1 # Keep screen on in terminal mode
  adv_camera: ^2.0.3+2 # in app camera for photoVerification
  app_tracking_transparency: ^2.0.2+4 # iOS app tracking transparency
  flutter_native_timezone: ^2.0.0
  notification_permissions: ^0.6.1
  nfc_manager: 3.2.0
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  chopper_generator: ^6.0.0
  drift_dev: ^2.6.0
  hive_generator: ^2.0.0
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/app_icon.png"
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages